import type { StoreData } from './types'

/** Real inventory from D:\\Cloude\\projects + known prod hosts (2026-09). */
export const SEED_VERSION = 'cloude-inventory-2026-09-13'

export const cloudeSeed: StoreData = {
  projects: [
    {
      id: 'p_hazina',
      name: 'Hazina',
      slug: 'hazina',
      description: 'Loyalty platform — customers, merchants, branches, Telegram flows, POS sync.',
      status: 'online',
      stack: ['Go', 'Fiber', 'Postgres', 'Redis', 'Docker'],
      updatedAt: '2026-09-13T00:00:00Z',
    },
    {
      id: 'p_caravan',
      name: 'Caravan Dispatcher',
      slug: 'caravan',
      description: 'Yuk xizmati — Telegram bot, admin, Click/Payme to‘lovlar.',
      status: 'online',
      stack: ['Django', 'aiogram', 'Celery', 'Postgres', 'Redis'],
      updatedAt: '2026-09-13T00:00:00Z',
    },
    {
      id: 'p_itzone',
      name: 'IT-Zone / Driver',
      slug: 'it-zone',
      description: 'Zarbdor driver API, Docker Panel (server.it-zone.uz), related services.',
      status: 'online',
      stack: ['Django', 'Next.js', 'Docker', 'Nginx'],
      updatedAt: '2026-09-13T00:00:00Z',
    },
    {
      id: 'p_eduflix',
      name: 'Eduflix',
      slug: 'eduflix',
      description: 'O‘quv markazi CRM — academic, finance, SMS (Eskiz).',
      status: 'online',
      stack: ['Django', 'Celery', 'Postgres', 'Redis'],
      updatedAt: '2026-09-13T00:00:00Z',
    },
    {
      id: 'p_crm',
      name: 'Learning CRM',
      slug: 'learning-crm',
      description: 'O‘quv markazi CRM + Telegram bot + OpenAI.',
      status: 'online',
      stack: ['Django', 'aiogram', 'OpenAI'],
      updatedAt: '2026-09-13T00:00:00Z',
    },
    {
      id: 'p_edu_crm',
      name: 'Edu CRM',
      slug: 'edu-crm',
      description: 'Teacher/student CRM — Django + Next.js.',
      status: 'online',
      stack: ['Django', 'Next.js', 'JWT'],
      updatedAt: '2026-09-13T00:00:00Z',
    },
    {
      id: 'p_hotel',
      name: 'Mehmonxona',
      slug: 'mehmonxona',
      description: 'Mehmon hona — FastAPI + Telegram bot.',
      status: 'pending',
      stack: ['FastAPI', 'python-telegram-bot'],
      updatedAt: '2026-09-13T00:00:00Z',
    },
    {
      id: 'p_yoshlar',
      name: 'Yoshlar Nazorat',
      slug: 'yoshlar',
      description: 'Flutter app + Laravel backend + face service.',
      status: 'online',
      stack: ['Flutter', 'Laravel'],
      updatedAt: '2026-09-13T00:00:00Z',
    },
    {
      id: 'p_cam',
      name: 'Cam / Smart Gate',
      slug: 'cam',
      description: 'Parking/gate — plate recognition (OpenCV / EasyOCR).',
      status: 'pending',
      stack: ['Django', 'React', 'OpenCV'],
      updatedAt: '2026-09-13T00:00:00Z',
    },
    {
      id: 'p_nexus',
      name: 'Nexus (IT Management)',
      slug: 'nexus',
      description: 'Productivity dashboard — Django + Celery + Redis.',
      status: 'pending',
      stack: ['Django', 'Celery', 'Redis'],
      updatedAt: '2026-09-13T00:00:00Z',
    },
    {
      id: 'p_local',
      name: 'Local workstation',
      slug: 'local-pc',
      description: 'Windows PC (User 1) — D:\\Cloude\\projects, Docker Desktop.',
      status: 'degraded',
      stack: ['Windows', 'Docker Desktop', 'Vite'],
      updatedAt: '2026-09-13T00:00:00Z',
    },
  ],

  applications: [
    {
      id: 'a_hazina_api',
      name: 'Hazina API',
      projectId: 'p_hazina',
      type: 'api',
      url: 'https://tback.myhazina.uz',
      status: 'online',
      version: 'prod',
      deploys: 0,
      latencyMs: 0,
    },
    {
      id: 'a_hazina_admin',
      name: 'Hazina Admin',
      projectId: 'p_hazina',
      type: 'web',
      url: 'https://cpanel.myhazina.uz',
      status: 'online',
      version: 'prod',
      deploys: 0,
      latencyMs: 0,
    },
    {
      id: 'a_hazina_web',
      name: 'Hazina Web',
      projectId: 'p_hazina',
      type: 'web',
      url: 'https://hazina.uz',
      status: 'online',
      version: 'prod',
      deploys: 0,
      latencyMs: 0,
    },
    {
      id: 'a_caravan_web',
      name: 'Caravan Admin',
      projectId: 'p_caravan',
      type: 'web',
      url: 'https://caravandispatcher.uz',
      status: 'online',
      version: 'prod',
      deploys: 0,
      latencyMs: 0,
    },
    {
      id: 'a_driver',
      name: 'Driver (Zarbdor)',
      projectId: 'p_itzone',
      type: 'web',
      url: 'https://zarbdor.drayver.it-zone.uz',
      status: 'online',
      version: 'prod',
      deploys: 0,
      latencyMs: 0,
    },
    {
      id: 'a_panel',
      name: 'Docker Panel',
      projectId: 'p_itzone',
      type: 'web',
      url: 'https://server.it-zone.uz',
      status: 'online',
      version: 'prod',
      deploys: 0,
      latencyMs: 0,
    },
    {
      id: 'a_eduflix',
      name: 'Eduflix',
      projectId: 'p_eduflix',
      type: 'web',
      url: 'https://eduflix.uz',
      status: 'online',
      version: 'prod',
      deploys: 0,
      latencyMs: 0,
    },
    {
      id: 'a_eduflix_api',
      name: 'Eduflix API',
      projectId: 'p_eduflix',
      type: 'api',
      url: 'https://api.eduflix.uz',
      status: 'online',
      version: 'prod',
      deploys: 0,
      latencyMs: 0,
    },
    {
      id: 'a_meridian',
      name: 'Meridian UI',
      projectId: 'p_local',
      type: 'web',
      url: 'http://localhost:5174',
      status: 'online',
      version: '0.1.0',
      deploys: 0,
      latencyMs: 0,
    },
  ],

  domains: [
    {
      id: 'd_hazina',
      name: 'hazina.uz',
      projectId: 'p_hazina',
      registrar: 'UZINFOCOM',
      ssl: 'valid',
      expiresAt: '—',
      dns: 'ok',
      status: 'active',
    },
    {
      id: 'd_myhazina',
      name: 'myhazina.uz',
      projectId: 'p_hazina',
      registrar: 'UZINFOCOM',
      ssl: 'valid',
      expiresAt: '—',
      dns: 'ok',
      status: 'active',
    },
    {
      id: 'd_tback',
      name: 'tback.myhazina.uz',
      projectId: 'p_hazina',
      registrar: 'Cloudflare / DNS',
      ssl: 'valid',
      expiresAt: '—',
      dns: 'ok',
      status: 'active',
    },
    {
      id: 'd_back_my',
      name: 'back.myhazina.uz',
      projectId: 'p_hazina',
      registrar: 'DNS',
      ssl: 'valid',
      expiresAt: '—',
      dns: 'ok',
      status: 'active',
    },
    {
      id: 'd_cpanel',
      name: 'cpanel.myhazina.uz',
      projectId: 'p_hazina',
      registrar: 'DNS',
      ssl: 'valid',
      expiresAt: '—',
      dns: 'ok',
      status: 'active',
    },
    {
      id: 'd_merchant',
      name: 'merchant.myhazina.uz',
      projectId: 'p_hazina',
      registrar: 'DNS',
      ssl: 'valid',
      expiresAt: '—',
      dns: 'ok',
      status: 'active',
    },
    {
      id: 'd_branch',
      name: 'branch.myhazina.uz',
      projectId: 'p_hazina',
      registrar: 'DNS',
      ssl: 'valid',
      expiresAt: '—',
      dns: 'ok',
      status: 'active',
    },
    {
      id: 'd_caravan',
      name: 'caravandispatcher.uz',
      projectId: 'p_caravan',
      registrar: 'UZINFOCOM',
      ssl: 'valid',
      expiresAt: '—',
      dns: 'ok',
      status: 'active',
    },
    {
      id: 'd_itzone',
      name: 'it-zone.uz',
      projectId: 'p_itzone',
      registrar: 'UZINFOCOM',
      ssl: 'valid',
      expiresAt: '—',
      dns: 'ok',
      status: 'active',
    },
    {
      id: 'd_server_itzone',
      name: 'server.it-zone.uz',
      projectId: 'p_itzone',
      registrar: 'DNS A',
      ssl: 'none',
      expiresAt: '—',
      dns: 'ok',
      status: 'active',
    },
    {
      id: 'd_driver',
      name: 'zarbdor.drayver.it-zone.uz',
      projectId: 'p_itzone',
      registrar: 'DNS',
      ssl: 'valid',
      expiresAt: '—',
      dns: 'ok',
      status: 'active',
    },
    {
      id: 'd_eduflix',
      name: 'eduflix.uz',
      projectId: 'p_eduflix',
      registrar: 'UZINFOCOM',
      ssl: 'valid',
      expiresAt: '—',
      dns: 'ok',
      status: 'active',
    },
    {
      id: 'd_eduflix_api',
      name: 'api.eduflix.uz',
      projectId: 'p_eduflix',
      registrar: 'DNS',
      ssl: 'valid',
      expiresAt: '—',
      dns: 'ok',
      status: 'active',
    },
  ],

  servers: [
    {
      id: 's_hazina',
      name: 'hazina-prod',
      projectId: 'p_hazina',
      provider: 'VPS',
      region: 'UZ / EU',
      ip: '185.191.141.224',
      status: 'online',
      cpu: 0,
      ram: 0,
      disk: 0,
      uptime: 'prod',
    },
    {
      id: 's_itzone',
      name: 'server.it-zone.uz',
      projectId: 'p_itzone',
      provider: 'Kali Linux VPS',
      region: 'UZ',
      ip: 'server.it-zone.uz',
      status: 'online',
      cpu: 0,
      ram: 0,
      disk: 0,
      uptime: 'prod',
    },
    {
      id: 's_local',
      name: 'local-windows',
      projectId: 'p_local',
      provider: 'This PC',
      region: 'Local',
      ip: '127.0.0.1',
      status: 'degraded',
      cpu: 0,
      ram: 0,
      disk: 0,
      uptime: 'Docker Desktop stopped',
    },
  ],

  containers: [
    // Hazina prod
    {
      id: 'c_hazina',
      name: 'hazina',
      projectId: 'p_hazina',
      serverId: 's_hazina',
      image: 'hazina app',
      status: 'online',
      ports: '8080',
      notes: 'compose.prod.yaml',
    },
    {
      id: 'c_hazina_db',
      name: 'hazina-database',
      projectId: 'p_hazina',
      serverId: 's_hazina',
      image: 'postgres',
      status: 'online',
      ports: '5432',
    },
    {
      id: 'c_hazina_redis',
      name: 'hazina-redis',
      projectId: 'p_hazina',
      serverId: 's_hazina',
      image: 'redis',
      status: 'online',
      ports: '6379',
    },
    {
      id: 'c_hazina_nginx',
      name: 'hazina-nginx',
      projectId: 'p_hazina',
      serverId: 's_hazina',
      image: 'nginx',
      status: 'online',
      ports: '80/443',
    },
    {
      id: 'c_hazina_certbot',
      name: 'hazina-certbot',
      projectId: 'p_hazina',
      serverId: 's_hazina',
      image: 'certbot',
      status: 'online',
      ports: '—',
      notes: 'SSL renew',
    },
    // Docker panel on it-zone
    {
      id: 'c_panel_engine',
      name: 'docker-panel-engine',
      projectId: 'p_itzone',
      serverId: 's_itzone',
      image: 'docker-panel',
      status: 'online',
      ports: '127.0.0.1:8080',
    },
    {
      id: 'c_panel_be',
      name: 'docker-panel-backend',
      projectId: 'p_itzone',
      serverId: 's_itzone',
      image: 'django',
      status: 'online',
      ports: 'internal',
    },
    {
      id: 'c_panel_fe',
      name: 'docker-panel-frontend',
      projectId: 'p_itzone',
      serverId: 's_itzone',
      image: 'next.js',
      status: 'online',
      ports: 'internal',
    },
    {
      id: 'c_panel_ngx',
      name: 'docker-panel-nginx',
      projectId: 'p_itzone',
      serverId: 's_itzone',
      image: 'nginx',
      status: 'online',
      ports: 'via host nginx',
    },
    // Caravan (prod stack names)
    {
      id: 'c_caravan_django',
      name: 'django_container_prod',
      projectId: 'p_caravan',
      serverId: 's_itzone',
      image: 'caravan django',
      status: 'online',
      ports: 'via nginx',
      notes: 'caravan_bot prod compose',
    },
    {
      id: 'c_caravan_bot',
      name: 'bot_container_prod',
      projectId: 'p_caravan',
      serverId: 's_itzone',
      image: 'aiogram bot',
      status: 'online',
      ports: '—',
    },
    {
      id: 'c_caravan_pg',
      name: 'postgres_container_prod',
      projectId: 'p_caravan',
      serverId: 's_itzone',
      image: 'postgres',
      status: 'online',
      ports: '5432',
    },
    {
      id: 'c_caravan_redis',
      name: 'redis_container_prod',
      projectId: 'p_caravan',
      serverId: 's_itzone',
      image: 'redis',
      status: 'online',
      ports: '6379',
    },
    {
      id: 'c_caravan_celery',
      name: 'celery_worker_container_prod',
      projectId: 'p_caravan',
      serverId: 's_itzone',
      image: 'celery',
      status: 'online',
      ports: '—',
    },
    {
      id: 'c_caravan_beat',
      name: 'celery_beat_container_prod',
      projectId: 'p_caravan',
      serverId: 's_itzone',
      image: 'celery beat',
      status: 'online',
      ports: '—',
    },
    {
      id: 'c_caravan_nginx',
      name: 'nginx_prod',
      projectId: 'p_caravan',
      serverId: 's_itzone',
      image: 'nginx',
      status: 'online',
      ports: '80/443',
    },
    // Driver
    {
      id: 'c_driver_be',
      name: 'driver-backend',
      projectId: 'p_itzone',
      serverId: 's_itzone',
      image: 'django/drf',
      status: 'online',
      ports: 'via nginx',
    },
    {
      id: 'c_driver_fe',
      name: 'driver-frontend',
      projectId: 'p_itzone',
      serverId: 's_itzone',
      image: 'next.js',
      status: 'online',
      ports: 'via nginx',
    },
    {
      id: 'c_driver_db',
      name: 'driver-db',
      projectId: 'p_itzone',
      serverId: 's_itzone',
      image: 'postgres',
      status: 'online',
      ports: '5432',
    },
    {
      id: 'c_driver_redis',
      name: 'driver-redis',
      projectId: 'p_itzone',
      serverId: 's_itzone',
      image: 'redis',
      status: 'online',
      ports: '6379',
    },
    // Eduflix
    {
      id: 'c_edu_web',
      name: 'eduflix-web',
      projectId: 'p_eduflix',
      serverId: 's_hazina',
      image: 'django',
      status: 'online',
      ports: 'via nginx',
      notes: 'docker/docker-compose.yml stack',
    },
    {
      id: 'c_edu_db',
      name: 'eduflix-db',
      projectId: 'p_eduflix',
      serverId: 's_hazina',
      image: 'postgres',
      status: 'online',
      ports: '5432',
    },
    {
      id: 'c_edu_redis',
      name: 'eduflix-redis',
      projectId: 'p_eduflix',
      serverId: 's_hazina',
      image: 'redis',
      status: 'online',
      ports: '6379',
    },
    {
      id: 'c_edu_celery',
      name: 'eduflix-celery_worker',
      projectId: 'p_eduflix',
      serverId: 's_hazina',
      image: 'celery',
      status: 'online',
      ports: '—',
    },
    {
      id: 'c_edu_beat',
      name: 'eduflix-celery_beat',
      projectId: 'p_eduflix',
      serverId: 's_hazina',
      image: 'celery beat',
      status: 'online',
      ports: '—',
    },
    // Local — Docker Desktop currently stopped
    {
      id: 'c_local_docker',
      name: 'docker-desktop-engine',
      projectId: 'p_local',
      serverId: 's_local',
      image: 'Docker Desktop',
      status: 'offline',
      ports: 'npipe',
      notes: 'com.docker.service Stopped (2026-09-13 scan)',
    },
  ],

  bots: [
    {
      id: 'b_yuk',
      name: 'YukXizmati Bot',
      projectId: 'p_caravan',
      platform: 'telegram',
      handle: '@YukXizmati_Bot',
      status: 'online',
      notes: 'caravan_bot — freight / dispatch',
    },
    {
      id: 'b_caravan_post',
      name: 'Caravan Post Forwarder',
      projectId: 'p_caravan',
      platform: 'telegram',
      handle: 'caravan-post',
      status: 'online',
      notes: 'Group message forwarder (old → new)',
    },
    {
      id: 'b_hazina',
      name: 'Hazina Telegram bots',
      projectId: 'p_hazina',
      platform: 'telegram',
      handle: 'hazina flows',
      status: 'online',
      notes: 'Platform built-in bots / webhooks',
    },
    {
      id: 'b_crm',
      name: 'Learning CRM Bot',
      projectId: 'p_crm',
      platform: 'telegram',
      handle: 'crm bot',
      status: 'online',
      notes: 'aiogram + OpenAI messaging',
    },
    {
      id: 'b_hotel',
      name: 'Mehmonxona Bot',
      projectId: 'p_hotel',
      platform: 'telegram',
      handle: 'hotel bot',
      status: 'pending',
      notes: 'python-telegram-bot',
    },
  ],

  integrations: [
    {
      id: 'i_iiko',
      name: 'iiko',
      provider: 'iiko',
      projectId: 'p_hazina',
      category: 'pos',
      status: 'active',
      connectedAt: '2025-01-01',
    },
    {
      id: 'i_moysklad',
      name: 'MoySklad',
      provider: 'moysklad',
      projectId: 'p_hazina',
      category: 'pos',
      status: 'active',
      connectedAt: '2025-01-01',
    },
    {
      id: 'i_poster',
      name: 'Poster',
      provider: 'poster',
      projectId: 'p_hazina',
      category: 'pos',
      status: 'active',
      connectedAt: '2025-01-01',
    },
    {
      id: 'i_payme_h',
      name: 'Payme',
      provider: 'payme',
      projectId: 'p_hazina',
      category: 'payment',
      status: 'active',
      connectedAt: '2025-01-01',
    },
    {
      id: 'i_click',
      name: 'Click',
      provider: 'click',
      projectId: 'p_caravan',
      category: 'payment',
      status: 'active',
      connectedAt: '2025-01-01',
    },
    {
      id: 'i_payme_c',
      name: 'Payme',
      provider: 'payme',
      projectId: 'p_caravan',
      category: 'payment',
      status: 'active',
      connectedAt: '2025-01-01',
    },
    {
      id: 'i_eskiz',
      name: 'Eskiz SMS',
      provider: 'eskiz',
      projectId: 'p_eduflix',
      category: 'sms',
      status: 'active',
      connectedAt: '2025-01-01',
    },
    {
      id: 'i_openai_crm',
      name: 'OpenAI',
      provider: 'openai',
      projectId: 'p_crm',
      category: 'ai',
      status: 'active',
      connectedAt: '2025-01-01',
    },
    {
      id: 'i_openai_caravan',
      name: 'OpenAI',
      provider: 'openai',
      projectId: 'p_caravan',
      category: 'ai',
      status: 'active',
      connectedAt: '2025-01-01',
    },
    {
      id: 'i_vercel_admin',
      name: 'Vercel (hazina_admin)',
      provider: 'vercel',
      projectId: 'p_hazina',
      category: 'ci',
      status: 'active',
      connectedAt: '2025-01-01',
    },
    {
      id: 'i_vercel_web',
      name: 'Vercel (hazina_web)',
      provider: 'vercel',
      projectId: 'p_hazina',
      category: 'ci',
      status: 'active',
      connectedAt: '2025-01-01',
    },
    {
      id: 'i_oauth_g',
      name: 'Google OAuth',
      provider: 'google',
      projectId: 'p_hazina',
      category: 'auth',
      status: 'active',
      connectedAt: '2025-01-01',
    },
    {
      id: 'i_oauth_fb',
      name: 'Facebook OAuth',
      provider: 'facebook',
      projectId: 'p_hazina',
      category: 'auth',
      status: 'active',
      connectedAt: '2025-01-01',
    },
  ],
}
